def pivot_results():
    sql = """
            RESUMEN AS (
            
				SELECT *,'PROACTIVO' FROM  RESOLUCION_70_1
            UNION
            SELECT *,'REACTIVO' FROM RESOLUCION_70_REACTIVO
            UNION
            SELECT *,'ACCESOS' FROM RESOLUCION_70_ACCESOS)
  
  SELECT SUM(REACTIVO_G) REACTIVO_G, SUM(REACTIVO_P) REACTIVO_P,SUM(REACTIVO_PP) REACTIVOPP,
			 SUM(ACCESOS_G) ACCESOS_G, SUM(ACCESOS_P) ACCESOS_P,SUM(ACCESOS_PP) ACCESOS_PP,
			 SUM(PROACTIVO_G) PROACTIVO_G, SUM(PROACTIVO_P) PROACTIVO_P,SUM(PROACTIVO_PP) PROACTIVO_PP  
			 FROM (         
   			SELECT 
					CASE
						WHEN PROACTIVO="REACTIVO" THEN SUMA_G
						END REACTIVO_G,
					CASE
						WHEN PROACTIVO="REACTIVO" THEN SUMA_P
						END REACTIVO_P,
				   CASE
						WHEN PROACTIVO="REACTIVO" THEN PORCENTAJE
						END REACTIVO_PP,
					CASE
						WHEN PROACTIVO="ACCESOS" THEN SUMA_G
						END ACCESOS_G,
					CASE
						WHEN PROACTIVO="ACCESOS" THEN SUMA_P
						END ACCESOS_P,
				   CASE
						WHEN PROACTIVO="ACCESOS" THEN PORCENTAJE
						END ACCESOS_PP,
					CASE
						WHEN PROACTIVO="PROACTIVO" THEN SUMA_G
						END PROACTIVO_G,
					CASE
						WHEN PROACTIVO="PROACTIVO" THEN SUMA_P
						END PROACTIVO_P,
				   CASE
						WHEN PROACTIVO="PROACTIVO" THEN PORCENTAJE
						END PROACTIVO_PP
				
				 FROM (
						SELECT SUMA_G,SUMA_P, (SUMA_G / TOTAL)*100 PORCENTAJE,PROACTIVO 
							FROM(
								SELECT
			   					SUM(RESOLUCION_70_G) SUMA_G,SUM(RESOLUCION_70_P)SUMA_P,PROACTIVO,(SUM(RESOLUCION_70_G)  + SUM(RESOLUCION_70_P)) TOTAL 
				
				 					FROM RESUMEN GROUP BY PROACTIVO 
								 ) 
						A) 
			B ) 
			C
    
    """