WITH
            tickets_formateados AS (
            SELECT *,
CASE
        WHEN date_format(PRO7.FECHA_APERTURA, "%d-%m-%Y")=date_format(PRO7.FECHA_CIERRE, "%d-%m-%Y") then "TNH" 
        WHEN date_format(PRO7.FECHA_APERTURA, "%d-%m-%Y") < date_format(PRO7.FECHA_CIERRE, "%d-%m-%Y") then "TH"       
		  WHEN date_format(PRO7.FECHA_APERTURA, "%d-%m-%Y") > date_format(PRO7.FECHA_CIERRE, "%d-%m-%Y") then "REVISAR"
        else null
        END  VALIDACION_TICKET_HEREDADO,
CASE
-- VALIDACION TIPO ENLACE EN TICKET
WHEN PRO7.ID_SERVICIO = 0  then "TICKET SIN ENLACE"
WHEN PRO7.ID_SERVICIO = "None" OR PRO7.ID_SERVICIO = NULL then "TICKET SIN ENLACE"
WHEN PRO7.ID_SERVICIO LIKE '%MASIV%'  then "MASIVA"
WHEN PRO7.ID_SERVICIO LIKE '%CC_%' then "TICKET CON ID DE CPE"
else "TICKET CON ENLACE"
END VALIDACION_TIPO_ENLACE_EN_TICKET
FROM (
SELECT *,
CASE
        WHEN PRO6.MES_CIERRE = NULL  AND PRO6.ANO_CIERRE = NULL  then "FECHA_INVALIDA"
        else "FECHA_VALIDA"
        END VALIDACION_FECHA,
CASE
-- VALIDACION DE TIKETS SI CORRESPONDE AL PERIODO.
        WHEN PRO6.MES_APERTURA=PRO6.MES_CIERRE AND PRO6.ANO_APERTURA=PRO6.ANO_CIERRE then "TICKET ABIERTO Y CERRADO EN MISMO PERIODO"
                else "TICKET ABIERTO Y CERRADO EN DISTINTO PERIODO"
   END VALIDACION_FECHA_2
FROM(
SELECT *,
CASE
        WHEN PRO5.T_RESOLUCION_AFECTACION_SIN_AFECTACION_HORAS <= 8 then "t<=8 horas"
        WHEN PRO5.T_RESOLUCION_AFECTACION_SIN_AFECTACION_HORAS > 8 then "t>8 horas"
END T_8_HORAS_RESOLUCION_AFECTACION_SIN_AFECTACION,
-- T 8 HORAS RESOLUCION AFECTACION / SIN AFECTACION
CASE
        WHEN PRO5.T_RESOLUCION_AFECTACION_SIN_AFECTACION_HORAS <= 12 then "t<=12 horas"
        WHEN PRO5.T_RESOLUCION_AFECTACION_SIN_AFECTACION_HORAS > 12 then "t>12 horas"
END T_12_HORAS_RESOLUCION_AFECTACION_SIN_AFECTACION,
-- T 12 HORAS RESOLUCION AFECTACION / SIN AFECTACION
-- VALIDACION DE CATEGORIA ESCALADO A BO
CASE
        WHEN PRO5.CATEGORIA ="DX - AFECTACION MASIVA" then "NO VALIDA"
        WHEN PRO5.CATEGORIA = "DX - BOLETA MAL ABIERTA" then "NO VALIDA"
        ELSE "VALIDA"
        END VALIDACION_CATEGORIA_ESCALADO_A_BO,
-- VALIDACION CATEGORIA DESCARTAR DX - AFECTACION MASIVA
CASE
        WHEN PRO5.CATEGORIA  <> "DX - AFECTACION MASIVA" then "SIN DX AFECTACION MASIVA"
        else "CON DX AFECTACION MASIVA"
        END VALIDACION_CATEGORIA_DESCARTAR_DX_AFECTACION_MASIVA,
YEAR(PRO5.FECHA_CIERRE) ANO_CIERRE,
MONTH(PRO5.FECHA_APERTURA) MES_APERTURA,
YEAR(PRO5.FECHA_APERTURA) ANO_APERTURA
FROM (
SELECT *,
(PRO4.T_RESOLUCION_AFECTACION_SIN_AFECTACION_minutos/60) T_RESOLUCION_AFECTACION_SIN_AFECTACION_HORAS

FROM (
                SELECT *,
                        CASE
                                WHEN PRO3.T_RESOLUCION <= 30 then "t<=30 min"
                                WHEN PRO3.T_RESOLUCION > 30 then "t>30 min"
                        END T_30_RESOLUCION,
                        CASE
                                WHEN PRO3.T_RESOLUCION <= 60 then "t<=60 min"
                                WHEN PRO3.T_RESOLUCION > 60 then "t>60 min"
                        END T_60_RESOLUCION,
                        CASE
                                WHEN PRO3.T_RESOLUCION <= 120 then "t<=120 min"
                                WHEN PRO3.T_RESOLUCION > 120 then "t>120 min"
                        END T_120_RESOLUCION,
                        CASE
                                WHEN PRO3.ID_SERVICIO LIKE '%DEFAULT%'
                                        OR  PRO3.ID_SERVICIO LIKE '%MASIVO%'
                                        OR  PRO3.ID_SERVICIO LIKE '%ESC_HN_DEF001%'
                                        OR PRO3.ID_SERVICIO <> "XT - ACCESO EMPRESARIAL"
                                        OR PRO3.ID_SERVICIO <> "XT - ACCESO ACTIVOS"
                                        OR PRO3.ID_SERVICIO <> "XT - ACCESO DATA_CENTER"
                                        OR PRO3.ID_SERVICIO <> "XT - DATOS"
                                        OR PRO3.ID_SERVICIO <> "0"
                                        OR PRO3.ID_SERVICIO <> 0
                                        OR PRO3.ID_SERVICIO  <> ""
                                        OR PRO3.FEMTOCELDA= "NO FEMTOCELDA"
                                        OR PRO3.CATEGORIA <> "DX - AFECTACION MASIVA"
                                        OR PRO3.TIPO_SERVICIO <> "NO_CMDB" then "VALIDO"
                                        else "NO VALIDO" END VALIDACION_REINCIDENCIA,
                        -- RESOLUCION DE AFECTACION EN MINUTOS
                        (PRO3.Open+Work_In_Progress+PRO3.Pending_Vendor+PRO3.Pending_Other+WO_Open+PRO3.WO_Not_Assigned+PRO3.WO_Pending_Supervisor+PRO3.WO_Worker_Assigned+WO_Pending_Worker+WO_Work_In_Progress+PRO3.WO_Pending_Vendor+PRO3.WO_Pending_Other+PRO3.
WO_Resolved+PRO3.Resolved) T_RESOLUCION_AFECTACION_SIN_AFECTACION_minutos
 FROM (
                SELECT *,
                (T_RESOLUCION_DX_AFECTACION_MASIVA+T_RESOLUCION_WO_PENDING_VENDOR+T_RESOLUCION_WO_PENDING_OTHER) T_RESOLUCION
 FROM (
        SELECT *,
                CASE
                        WHEN PRO1.MASIVO="ASOCIADO A MASIVA" or PRO1.MASIVO="MASIVA" then
                        PRO1.Open+PRO1.Work_In_Progress+PRO1.Pending_Vendor+PRO1.Pending_Other+PRO1.WO_Not_Assigned+PRO1.WO_Resolved
                        ELSE
                        PRO1.Open+PRO1.Work_In_Progress+PRO1.Pending_Vendor+PRO1.Pending_Other+PRO1.WO_Not_Assigned+PRO1.WO_Resolved+Resolved
                        END T_RESOLUCION_DX_AFECTACION_MASIVA,
                CASE
                        WHEN UPPER(PRO1.PROVEEDOR) ='UNKNOWN' AND PRO1.Pending_Vendor>0 THEN WO_Pending_Vendor ELSE 0
                        END T_RESOLUCION_WO_PENDING_VENDOR,
                        PRO1.WO_Pending_Other T_RESOLUCION_WO_PENDING_OTHER

FROM (
SELECT *,
CASE
        WHEN RESPONSABLE = 'MASIVO_REACTIVO' OR  RESPONSABLE = 'MASIVO_PROACTIVO' THEN 'MASIVO_CORPORATIVO'     
        WHEN RESPONSABLE = 'MASIVO_CORPORATIVO' THEN 'MASIVO'
        ELSE 'NO ASOCIADO A MASIVA'
END MASIVO,
CASE
        WHEN SUBCATEGORY = "CLIENTE" THEN "CLIENTE" else "CLARO" END ATRIBUCION,
CASE
        WHEN TIPO_SERVICIO LIKE '%F%' THEN "FENTOCELDA" ELSE "NO FENTOCELDA" END FEMTOCELDA,
CASE
        WHEN GRUPO_WO ='None' OR GRUPO_WO ='' OR GRUPO_WO =NULL THEN "RESUELTO POR CNOC"
ELSE "RESUELTO POR OTRAS AREAS" END  VALIDACION_RESOLUCION,
CASE
        WHEN GRUPO_WO = 'None' THEN  'NO ESCALADO A BO'
        WHEN GRUPO_WO LIKE '%B.O%'  then "ESCALADO A BO"
        WHEN GRUPO_WO LIKE '%SEGURIDAD%' then "ESCALADO A BO"
        WHEN GRUPO_WO LIKE '%GESTION DATOS SV%' then "ESCALADO A BO"
        WHEN GRUPO_WO LIKE '%WIMAX%' then "ESCALADO A BO"
        ELSE "NO ESCALADO A BO"
END ESCALADO_A_BO, -- VALIDACION DE RESOLUCION
CASE
        WHEN Open > 0 then "OPEN VALIDO" else "OPEN INVALIDO"
END VALIDACION_OPEN,
CASE
        WHEN Open <> "" and Open <=10 then "t<=10 min"
        WHEN Open <> "" and Open > 10  then "t>10 min"
END T_10_OPEN,
CASE
        WHEN Open <> "" and OPEN <=15 then "t<=15 min"
        WHEN Open <> "" and OPEN > 15  then "t>15 min"
END T_15_OPEN
FROM fr_kpi_outsourcing1
) AS PRO1
) AS PRO2
) AS PRO3
) AS PRO4
) AS PRO5
) AS PRO6
) AS PRO7
INNER JOIN catalogo_areas_cnoc ON catalogo_areas_cnoc.nombre_area_claro = pro7.RESPONSABLE
WHERE PRO7.VALIDACION_FECHA="FECHA_VALIDA"
    ),
    TIKETS_ORDENADOS AS (
    SELECT *,DATE(FECHA_APERTURA) F_FECHA_APERTURA,(ELT(WEEKDAY(FECHA_APERTURA) + 1, 'Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado', 'Domingo')) AS DIA_SEMANA, HOUR(FECHA_APERTURA) H_APERTURA
	 FROM tickets_formateados WHERE FECHA_APERTURA NOT IN ('None') ORDER BY F_FECHA_APERTURA DESC),
    TIKETS_CONTADOS AS (
    SELECT F_FECHA_APERTURA, DIA_SEMANA ,H_APERTURA, COUNT(H_APERTURA) CONTAR FROM TIKETS_ORDENADOS 
    WHERE F_FECHA_APERTURA BETWEEN '20220601' AND '20220630' 
    GROUP BY F_FECHA_APERTURA,DIA_SEMANA,H_APERTURA  ORDER BY F_FECHA_APERTURA,H_APERTURA)
    
    SELECT *,TOTAL/24 FROM (
	 SELECT *,
H0+
H1+
H2+
H3+
H4+
H5+
H6+
H7+
H8+
H9+
H10+
H11+
H12+
H13+
H14+
H15+
H16+
H17+
H18+
H19+
H20+
H21+
H22+
H23 TOTAL 
FROM (
	 SELECT 
		 F_FECHA_APERTURA,
		 DIA_SEMANA,
	    SUM(H0) H0,
		SUM(H1) H1,
		SUM(H2) H2,
		SUM(H3) H3,
		SUM(H4) H4,
		SUM(H5) H5,
		SUM(H6) H6,
		SUM(H7) H7,
		SUM(H8) H8,
		SUM(H9) H9,
		SUM(H10) H10,
		SUM(H11) H11,
		SUM(H12) H12,
		SUM(H13) H13,
		SUM(H14) H14,
		SUM(H15) H15,
		SUM(H16) H16,
		SUM(H17) H17,
		SUM(H18) H18,
		SUM(H19) H19,
		SUM(H20) H20,
		SUM(H21) H21,
		SUM(H22) H22,
		SUM(H23) H23


FROM (
    SELECT F_FECHA_APERTURA,DIA_SEMANA,
				CASE  WHEN H_APERTURA=0 THEN CONTAR ELSE 0 END 'H0',
				CASE  WHEN H_APERTURA=1 THEN CONTAR ELSE 0 END 'H1',
				CASE  WHEN H_APERTURA=2 THEN CONTAR ELSE 0 END 'H2',
				CASE  WHEN H_APERTURA=3 THEN CONTAR ELSE 0 END 'H3',
				CASE  WHEN H_APERTURA=4 THEN CONTAR ELSE 0 END 'H4',
				CASE  WHEN H_APERTURA=5 THEN CONTAR ELSE 0 END 'H5',
				CASE  WHEN H_APERTURA=6 THEN CONTAR ELSE 0 END 'H6',
				CASE  WHEN H_APERTURA=7 THEN CONTAR ELSE 0 END 'H7',
				CASE  WHEN H_APERTURA=8 THEN CONTAR ELSE 0 END 'H8',
				CASE  WHEN H_APERTURA=9 THEN CONTAR ELSE 0 END 'H9',
				CASE  WHEN H_APERTURA=10 THEN CONTAR ELSE 0 END 'H10',
				CASE  WHEN H_APERTURA=11 THEN CONTAR ELSE 0 END 'H11',
				CASE  WHEN H_APERTURA=12 THEN CONTAR ELSE 0 END 'H12',
				CASE  WHEN H_APERTURA=13 THEN CONTAR ELSE 0 END 'H13',
				CASE  WHEN H_APERTURA=14 THEN CONTAR ELSE 0 END 'H14',
				CASE  WHEN H_APERTURA=15 THEN CONTAR ELSE 0 END 'H15',
				CASE  WHEN H_APERTURA=16 THEN CONTAR ELSE 0 END 'H16',
				CASE  WHEN H_APERTURA=17 THEN CONTAR ELSE 0 END 'H17',
				CASE  WHEN H_APERTURA=18 THEN CONTAR ELSE 0 END 'H18',
				CASE  WHEN H_APERTURA=19 THEN CONTAR ELSE 0 END 'H19',
				CASE  WHEN H_APERTURA=20 THEN CONTAR ELSE 0 END 'H20',
				CASE  WHEN H_APERTURA=21 THEN CONTAR ELSE 0 END 'H21',
				CASE  WHEN H_APERTURA=22 THEN CONTAR ELSE 0 END 'H22',
				CASE  WHEN H_APERTURA=23 THEN CONTAR ELSE 0 END 'H23'

FROM TIKETS_CONTADOS)A GROUP BY F_FECHA_APERTURA,DIA_SEMANA)B )C
    
    
